name: "[CD] Continuous Delivery"

#on:
#  push:
#    branches: [main]

on:
  pull_request:
    types: [opened, synchronize]
    
env:
  VERCEL_ORG_ID: team_MYQp19bJIVGD8hnULRA4eJru
  VERCEL_PROJECT_ID: prj_9mmwxV23m6oAxP6AfClZzha0gUk3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Dependencies"
        run: "npm i"
      - name: "Deploy"
        run: "npx vercel --prod --token=${{secrets.VERCEL_TOKEN}}"
